[package]
name = "wgpu-sort"
version = "0.1.0"
edition = "2024"
description = "High-performance, safe wgpu Radix Sort and Prefix Scan for Rust."
authors = ["samjsui"]
license = "MIT"
repository = "https://github.com/samjsui/wgpu-algorithms"
keywords = ["gpgpu", "wgpu", "sort", "radix", "compute"]
categories = ["algorithms", "graphics", "science"]
include = ["src/**/*.rs", "src/**/*.wgsl", "Cargo.toml", "README.md", "LICENSE"]
exclude = ["benches/*", "examples/*", "target/*"]

[dependencies]
wgpu = "29.0.3"
bytemuck = { version = "1.24", features = ["derive"] }
futures = "0.3.31"
log = "0.4.29"

[dev-dependencies]
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
rand = "0.10.1"
pollster = "0.4"
env_logger = "0.11.8"
criterion = { version = "0.8.1", features = ["async_tokio", "html_reports"] }
rayon = "1.10"
